name: emergency_app
description: A web-based emergency response app built with Flutter.

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  audioplayers: ^6.4.0
  shimmer: ^3.0.0
  google_fonts: ^6.2.1
  rive: ^0.13.20
  http: ^1.3.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  geolocator: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/buzzer.mp3    
    - assets/rive/particles.riv


